### ISSUE TITLE
Question about RDMA support

### ISSUE THREAD

**Issue by RecoderChris** [simbricks/simbricks#45]
Hi! I am interested in the end-to-end simulation with **an RDMA network**. Did SimBricks support RDMA features already? Or what else do I need to do to support the RDMA network (e.g. build a new RNIC simulator)?  Can you give me some advice on building a **simple** RDMA network based on SimBricks? Looking forward to your reply!! : )

**Comment by FreakyPenguin** [comment]
Hi @RecoderChris! Excellent question. Currently we do not have a working NIC simulator that supports RDMA yet. So that is indeed the missing piece. @csbingao is working on a simulator for Intel's e800 100G NIC with RDMA support (https://github.com/csbingao/simbricks/tree/nic-e810) but that will still take a bit of time until it is done. (turns out modern NICs are pretty complicated, who would have thought ;-)).

If you do not care about a realistic NIC and just need something that allows you to run RDMA apps, there might be a quicker but still implementation intensive way to get something to work. I recently came across QEMU's pvrdma support https://github.com/qemu/qemu/blob/master/docs/pvrdma.txt. From what I understand that's fully integrated (through VMware's efforts) into kernel and libraries, but has a much simpler HW interface (see the readme above). But the way this is implemented in QEMU is not suitable for SimBricks (it needs RDMA support on the host kernel, either through real hardware or rxe). In principle you could hack up something functional with rxe and somehow capturing the ethernet packets the kernel generates, but then you lose any ability to control the timing. So you would need to implement a NIC simulator with the pvrdma PCIe interface yourself, that speaks the PCIe interface on one side, and then does the appropriate RDMA things and implements the Ethernet interface on the other end. For the RDMA protocol bits https://github.com/inet-tub/ns3-datacenter might be a useful starting point (that repo contains an NS3-model for the RDMA protocol from what I remember). All in all even this approach would take a fair bit of hacking.

I hope this helps

**Comment by FreakyPenguin** [comment]
I've created #47 to track the status for RDMA support.

**Comment by FreakyPenguin** [comment]
I will close this for now. Please feel free re-open if you have follow-up questions.
