### ISSUE TITLE
How to simulate a simple LegoOS system with simbricks?

### ISSUE THREAD

**Issue by prokey2001** [simbricks/simbricks#61]
I have just read the paper"Improving Disaggregated System Evaluation with Modular End-to-End Simulation".This article briefly introduces how to simulate various components of LegoOS, but it is still unclear how to use the code from this repository to build LegoOS. As a classic work in the field of resource disaggregation, does this simulator provide corresponding tutorials to guide how to build a LegoOS system?

**Comment by hajeongee** [comment]
Hi @prokey2001,
 
Thank you for your interest in SimBricks and for raising this issue. We are happy to see your efforts in building a resource disaggregated system using SimBricks and are willing to help.

For general guidance on using SimBricks, please refer to our tutorial and documentation [here](https://simbricks.github.io/) (it's currently a work in progress though..). Although we do not have a guide specifically tailored for resource disaggregated systems, constructing a simulation for such a system using SimBricks should not deviate much from its primary usage.

In our paper, we presented a proof of concept for constructing LegoOS-like disaggregated systems using SimBricks. All the code for the component simulators and experiment scripts can be found in our main branch. For the experiment script, please refer to this [file](https://github.com/simbricks/simbricks/blob/main/experiments/pyexps/memswitch.py).

To simulate pComponent, we integrated gem5 with a hardware network controller through SimBricks' memory interface. In gem5, we attached a memory adapter to the memory bus, which forwards memory access requests to the hardware controller via the SimBricks channel. You can find the gem5 configuration [here](https://github.com/simbricks/gem5/blob/disaggregated/configs/simbricks/simbricks.py),   [(and the line might be interesting)](https://github.com/simbricks/gem5/blob/72b0af4256b131e0fc9c66377404b093cf7ef793/configs/simbricks/simbricks.py#L199) and memory adapter implementation [here](https://github.com/simbricks/gem5/blob/disaggregated/src/simbricks/mem.cc). The hardware network controller currently only wraps memory access requests into UDP packets and sends them through the network (and vice versa for the opposite direction), but you can add more functionalities as needed.

To recreate the exact system proposed by LegoOS, you will need to perform some additional work based on our implementation:

1.  Implement the missing hardware functionalities, such as TLBs and storage-related functionalities in mComponent, sComponent, etc.
2.  Port the Splitkernel OS to the simulated hardware environment. In LegoOS paper, certain aspects of the proposed system (e.g., ExCache misses) were emulated using page faults due to the unavailability of actual hardware. With SimBricks simulations, these parts of the original LegoOS implementation will require modifications once the hardware components have been implemented.

If you have any further questions, please do not hesitate to reach out. We are also available for discussions on our [Slack channel](https://join.slack.com/t/simbricks/shared_invite/zt-16y96155y-xspnVcm18EUkbUHDcSVonA).
