### ISSUE TITLE
about pcie switch.

### ISSUE THREAD

**Issue by lasthongye** [simbricks/simbricks#76]
Dear team, is it possible to integrate an emulator for a PCIe switch in the simbricks framework? Is there a simulator like this?

**Comment by lasthongye** [comment]
If necessary, we can provide some fees, which can be discussed in detail. My email is 12201540@qq.com , Tony Gu

**Comment by FreakyPenguin** [comment]
Hi @lasthongye,

sorry for the delay. This would definitely be possible, but the details of what you need will really depend on what you need and what the goal is.

If this is just about having two different PCI device simulators plugged into the same machine and having them do peer-to-peer DMA, then this should require little or now additional work, as I would expect the host simulator (e.g. gem5) to already do this correctly (worst case with some minimal fixing) if you just connect two devices directly to the host.

If, on the other hand, you want to model more low-level detail such as bottleneck in shared PCIe links between the switch and host, then this will get a lot more complicated. The current SimBricks PCIe interface is purposely kept simple for both ends and maximize compatiblity, and because of this expects only a single device to be connected to the other end. An alternative would be to introduce an additional more low-level SimBricks PCIe interface, e.g. raw PCIe TLP or even link-layer packets. This would then make it possible to model general PCIe elements like swtiches, etc. This would however be a significant implementation effort as this would require a completely re-designed PCIe adapter for gem5 that actually implements all of these gnarly PCIe endpoint details and adapts them to gem5. Here we are definitely talking at least a few week's worth of effort.

For other use cases (e.g. having PCIe devices shared between hosts), there may be more creative ways of getting the functionality you need without very deep modifications. If you can tell us more I can provide more detail.

Antoine

**Comment by lasthongye** [comment]
@FreakyPenguin 
Thank you very much for your reply. Can I communicate with you via email in future communication? Thank you again.

**Comment by jonas-kaufmann** [comment]
@lasthongye I'm closing this for now. Feel free to reopen if you have follow-up questions.
